"""Add aggregator setup

Revision ID: 9a4a70ce7876
Revises: 
Create Date: 2026-04-14 16:44:54.356502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9a4a70ce7876'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('creator',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_name'), 'creator', ['name'], unique=True)
    op.create_table('platform',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform_type', sa.Enum('YouTube', 'Instagram', 'TikTok', 'X', name='platformtype'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_name'), 'platform', ['name'], unique=True)
    op.create_table('post',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('media_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('post_type', sa.Enum('Text', 'Post', 'Story', 'Short', 'Video', name='posttype'), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraperconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('post_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active_from', sa.Time(), nullable=True),
    sa.Column('active_to', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'HARD_STOP', name='scraperstatus'), nullable=False),
    sa.Column('target_quality', sa.Integer(), nullable=False),
    sa.Column('exclude_shorts', sa.Boolean(), nullable=False),
    sa.Column('live_check_until', sa.DateTime(), nullable=True),
    sa.Column('schedule_config', sa.JSON(), nullable=False),
    sa.Column('trigger_type', sa.Enum('MANUAL', 'SCHEDULE', 'POST_DEPENDENT', 'DISCORD', name='scrapertriggertype'), nullable=False),
    sa.Column('trigger_config', sa.JSON(), nullable=True),
    sa.Column('dependency_post_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('discord_webhooks', sa.JSON(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('user_agent_override', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritepost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritepost')
    op.drop_table('scraperconfig')
    op.drop_table('post')
    op.drop_index(op.f('ix_platform_name'), table_name='platform')
    op.drop_table('platform')
    op.drop_index(op.f('ix_creator_name'), table_name='creator')
    op.drop_table('creator')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
